spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskflow_prod
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      leak-detection-threshold: 60000
  jpa:
    show-sql: false
  flyway:
    clean-disabled: true
    validate-on-migrate: true

logging:
  level:
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
    org.flywaydb: INFO
    com.yourpackage: INFO
  file:
    name: logs/taskflow.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: when-authorized
    metrics:
      access: none

jwt-keys:
  private_key: ${PRIV_KEY}
  public_key: ${PUB_KEY}
