name: TaskFlow-CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Print Java version
        run: java --version

      - name: Print Maven version
        run: mvn --version

      - name: Create JWT keys directory
        run: mkdir -p src/main/resources/jwt-keys

      - name: Generate JWT keys for testing
        run: |
          openssl genrsa -out src/main/resources/jwt-keys/private.pem 2048
          openssl rsa -in src/main/resources/jwt-keys/private.pem -pubout -out src/main/resources/jwt-keys/public.pem

      - name: Run tests
        run: mvn test
        env:
          SPRING_PROFILES_ACTIVE: test
          SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb
          SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.h2.Driver
          SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop

      - name: Build JAR
        run: mvn package -DskipTests 